### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by axelhuizinga** [small-cake/server#61]
> spawn-sync@1.0.15 postinstall /root/.nvm/versions/node/v7.10.1/lib/node_modules/muffin-cli/node_modules/spawn-sync
> node postinstall

module.js:471
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v7.10.1/lib/node_modules/muffin-cli/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-03T09_22_09_852Z-debug.log

**Comment by dotamir** [comment]
Try install it with yarn.
